todoprod/todo_list/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView

app_name = 'todo_list'

urlpatterns = [
    path("",views.ToDoListIndexView.as_view(), name='index'),
    path("list/",views.ToDoListView.as_view(), name='list'),
    path("done/",views.ToDoListDoneView.as_view(), name='done'),
    path("<int:pk>/",views.ToDoDetailView.as_view(), name='detail'),
]

todoprod/todoprod/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name= 'index.html'), name='index'),
    path('todos/', include('todo_list.urls')),
    path('admin/', admin.site.urls),
]

todoprod/todo_list/models.py
from django.db import models

# Create your models here.

class ToDoItem(models.Model):

    title = models.CharField(max_length=100)
    done = models.BooleanField(default=False)

    class Meta:
        ordering = 'id',
        verbose_name = 'ToDo item'


    def __str__(self):
        return self.title

todoprod/todo_list/views.py
from django.http import HttpRequest
from django.shortcuts import render
from .models import ToDoItem

from django.views.generic import DetailView, ListView

class ToDoListIndexView(ListView):
    template_name = "todo_list/index.html"
    queryset = ToDoItem.objects.all()[:3]


class ToDoListView(ListView):
    model = ToDoItem

class ToDoListDoneView(ListView):
    queryset = ToDoItem.objects.filter(done=True).all()

class ToDoDetailView(DetailView):
    model = ToDoItem

todoprod/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
    Base Title
    {% endblock title %}
  </title>
</head>
<body>
{% include 'components/navbar.html' %}
  {% block body %}
    Base body
  {% endblock body %}
<footer>
  &copy; Django TODO app
  {% block footer %}
  {% endblock %}
</footer>
</body>
</html>

todoprod/templates/components/navbar.html
<nav>
  <ul>
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'todo_list:index' %}">ToDo list</a></li>
    <li><a href="#">About</a></li>
  </ul>
</nav>

todoprod/templates/index.html
{% extends 'base.html' %}

{% block title %}
    ToDO APp Index
{% endblock title %}

{% block body %}
<h1> Welcome to our TODO APP! </h1>
<h2> Work in progress </h2>
<h3> Now is {% now "jS F Y H:i:s" %} </h3>
{% endblock body %}

todoprod/todo_list/templates/todo_list/base.html
{% extends 'base.html'%}

{% block footer %}
  ToDo list
{% endblock %}

todoprod/todo_list/templates/todo_list/components/todo_items_list.html
  <ul>
    {% for todo_item in object_list %}
    <li>
      <a href="{% url 'todo_list:detail' pk=todo_item.pk %}">
      {{ todo_item.title }}
      {% if todo_item.done %}
        ✅
          {% else %}
        ❌
      {% endif  %}
        </a>
      </li>
    {% endfor %}
  </ul>

todoprod/todo_list/templates/todo_list/index.html
{% extends 'todo_list/base.html'%}

{% block title %}
  ToDo list App
{% endblock %}

{% block body %}
  <h1>ToDo List App</h1>
  <div>
    <li><a href="{% url 'todo_list:list' %}">All todo items</a></li>
    <li><a href="{% url 'todo_list:done' %}">Done items</a></li>
  </div>
  <h2>Todos:</h2>
  {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todoprod/todo_list/templates/todo_list/todoitem_detail.html
{% extends 'base.html'%}

{% block title %}
  ToDo #{{ object.pk }}
{% endblock %}

{% block body %}
  <h3>Todo:</h3>
<div>
   <div>Title: <strong>{{ object.title }}</strong></div>
    <div>Status: <strong>{{ object.done }}</strong></div>
</div>
  {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todoprod/todo_list/templates/todo_list/todoitem_list.html
{% extends 'todo_list/base.html'%}

{% block title %}
  ToDo list
{% endblock %}

{% block body %}
  <h3>Todos:</h3>
  {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}